load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "cli",
    srcs = [
        "CLI.cpp",
        "Command.cpp",
    ],
    hdrs = [
        "CLI.hpp",
        "Command.hpp",
    ],
    visibility = ["//visibility:public"],
)
