load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "components",
    srcs = [
        "Home.cpp",
        "Device.cpp",
    ],
    hdrs = [
        "Home.hpp",
        "Room.hpp",
        "Device.hpp",
        "State.hpp",
    ],
    deps = [
        "//utils"
    ],
    visibility = ["//visibility:public"],
)
